version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
